---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
    - vars.yml
  tasks:
    - name: Test installation of HTCondor
      ansible.builtin.command: condor_status
      changed_when: false
