---
name: Ansible Lint

on:

  pull_request:
    branches: [ master ]

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6
